---
- name: set Timezone
  timezone:
    name: "{{ timezone | default('America/New_York') }}"
  notify: systemd-timesyncd configuration changed

- name: add Timesyncd Configuration
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed

- name: start and enable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
