---

- name: "rsyslog: copy config"
  copy:
    content: |
      module(load="omprog")
      module(load="mmutf8fix")
      action(type="mmutf8fix" replacementChar="?")
      action(type="omfwd" protocol="tcp" target="{{ remote_syslog.ip }}" port="{{ remote_syslog.port }}" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted" KeepAlive="on")
    dest: /etc/rsyslog.d/50-promtail.conf
  notify: rsyslog configuration changed

- name: "rsyslog: start systemd service"
  systemd:
    name: rsyslog
    enabled: true
    state: started
  # when: remote_syslog.enabled is defined and remote_syslog.enabled == true
