---

- name: set up remote syslog server (1/2)
  template:
    src: 50-promtail.conf.j2
    dest: /etc/rsyslog.d/50-promtail.conf
  notify: rsyslog configuration changed

- name: enable rsyslog service and assure it is started
  systemd:
    name: rsyslog
    enabled: true
    state: started
  # when: remote_syslog.enabled is defined and remote_syslog.enabled == true
