---
- box: ubuntu/focal64
  group: k8s
  name: master
  ip: 172.16.20.10
  vars:
    test: "hello1"
- box: ubuntu/focal64
  group: k8s
  name: worker-a
  ip: 172.16.20.11
  vars: 
    test: "hello2"
# - box: ubuntu/focal64
#   group: k8s
#   name: worker-b
#   ip: 172.16.20.12
# - box: ubuntu/focal64
#   group: k8s
#   name: worker-c
#   ip: 172.16.20.13
