---
version: '3'

vars:
  VMS:
    sh: vagrant status --machine-readable | grep metadata | cut -d, -f2

tasks:
  build:
    cmds:
    - |
      vagrant status --machine-readable | grep metadata | cut -d, -f2 | xargs --max-procs=4 -I {} vagrant up {}
      for vm in {{catLines .VMS}}; do
        VBoxManage snapshot "${vm}" take "baseline" --live;
      done
  init:
    cmds:
    - ansible-galaxy install -r requirements.yml
    - pip3 install -r requirement.txt || true
    - vagrant plugin install vagrant-vbguest
    - vagrant box update
  pull:
    cmds:
    - vagrant box update
    - vagrant box prune --keep-active-boxes
  ping:
    cmds:
    - ansible all --one-line -m ping -i inventory/virtualbox.yml
  list:
    cmds:
    - ansible all --list-hosts