---

- name: Remove motd
  command: update-rc.d motd remove

- name: Silence the login prompt
  file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
