---
all:
  children:
    master:
      hosts:
        k8s-master:
          ansible_host: 172.16.20.11
          k3s_control_node: true
          k3s_tls_san: 172.16.20.11
          k3s_node_ip_address: 172.16.20.11
    worker:
      hosts:
        k8s-worker-a:
          ansible_host: 172.16.20.12
          k3s_node_ip_address: 172.16.20.12
        k8s-worker-b:
          ansible_host: 172.16.20.13
          k3s_node_ip_address: 172.16.20.13
    longhorn:
      hosts:
        k8s-worker-a:
          ansible_host: 172.16.20.12
          k3s_node_ip_address: 172.16.20.12
        k8s-worker-b:
          ansible_host: 172.16.20.13
          k3s_node_ip_address: 172.16.20.13      
      vars:
        # Set 'manage_lvm' to false inorder to preserve data and skip the lvm role
        manage_lvm: true
        lvm_groups:
        - vgname: longhorn-vg
          disks:
          - /dev/sdc
          create: true
          lvnames:
          - lvname: lv0
            size: 100%FREE
            create: true
            filesystem: ext4
            mount: true
            mntp: /var/lib/longhorn
