---

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - br_netfilter
  - overlay

- name: Enable kernel modules on boot
  copy:
    content: "{{item.kernel_module}}"
    dest: "/etc/modules-load.d/{{item.name}}.conf"
  with_items:
  - { name: 'netfilter', kernel_module: 'br_netfilter' }
  - { name: 'overlay', kernel_module: 'overlay' }
