---
- name: Set Timezone
  timezone:
    name: "{{ timezone | default('America/New_York') }}"

- name: Add Timesyncd Configuration
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
    owner: root
    group: root

- name: Restart systemd-timesyncd service
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: restarted

- name: Start and enable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
