---

- name: remove ubuntu packages
  become: true
  apt:
    name: snapd
    state: absent
  with_items:
  - snapd
  - ubuntu-minimal
  - ubuntu-advantage-tools
  - apport
  - ubuntu-server
  - apport-symptoms
  - python3-apport
  - python3-problem-report
  - python3-systemd
  - sosreport
  - popularity-contest

- name: remove snap cruft
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/snap"
    - "/var/snap"
    - "/var/lib/snapd"
    - "/var/cache/snapd"
    - "/usr/lib/snapd"

- name: never allow snap to be installed
  become: true
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - "snapd"
