---
- name: Deploy Calico Operator
  become: false
  delegate_to: localhost
  command: "kubectl create -f {{ calico.operator_manifest }}"
  # register: calico_result
  environment:
    KUBECONFIG: "kubeconfig"
  ignore_errors: true
    # DATASTORE_TYPE: "kubernetes"
    # IP_AUTODETECTION_METHOD: "interface=enp0s8"
  # until: calico_result is succeeded
  # retries: 5
  # delay: 5

- name: Configure Calico Settings
  become: false
  delegate_to: localhost
  shell: |
    cat << EOF | kubectl create -f -
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          ipPools:
          - blockSize: 26
            cidr: 10.43.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
  environment:
    KUBECONFIG: "kubeconfig"
  ignore_errors: true
    # DATASTORE_TYPE: "kubernetes"
  # retries: 5
  # delay: 5
# - name: Deploy Calico Operator
#   k8s:
#     kubeconfig: