---

- name: Deploy Calico Operator
  become: false
  run_once: true
  delegate_to: localhost
  command: "kubectl create -f {{ calico.operator_manifest }}"
  environment:
    KUBECONFIG: "kubeconfig"
  ignore_errors: true

- name: Configure Calico Settings
  become: false
  run_once: true
  delegate_to: localhost
  shell: |
    cat << EOF | kubectl create -f -
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          ipPools:
          - blockSize: 26
            cidr: 10.43.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
  environment:
    KUBECONFIG: "kubeconfig"
  ignore_errors: true
