---

- name: Copy config file to user setup directory
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "../kubeconfig"
    owner: "{{ lookup('env', 'USER') }}"
    flat: true
  when: "'master' in group_names"

- name: Replace https://localhost:6443 by https://{{ k3s_control_node_address }}:6443
  become: false
  delegate_to: localhost
  run_once: true
  replace:
    path: "../kubeconfig"
    regexp: "https://127.0.0.1:6443"
    replace: "https://{{ k3s_control_node_address }}:6443"

- name: Create directory .kube
  delegate_to: localhost
  become: false
  run_once: true
  file:
    path: ~/.kube
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
  when: kubeconfig == true

- name: Copy config file to user home directory
  delegate_to: localhost
  run_once: true
  become: false
  copy:
    src: "../kubeconfig"
    dest: "~/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    flat: true
  when: kubeconfig == true
