---

- name: "cluster-meta: apply master taints"
  become: false
  delegate_to: localhost
  command: kubectl taint --overwrite node {{ ansible_hostname }} node-role.kubernetes.io/master=true:NoSchedule
  environment:
    KUBECONFIG: "{{ inventory_dir | dirname }}/kubeconfig"
  when:
  - "'master' in group_names"

- name: "cluster-meta: apply worker annotations"
  become: false
  delegate_to: localhost
  command: kubectl label --overwrite node {{ ansible_hostname }} node-role.kubernetes.io/worker=true
  environment:
    KUBECONFIG: "{{ inventory_dir | dirname }}/kubeconfig"
  when:
  - "'worker' in group_names"

- name: "cluster-meta: apply system-upgrade annotations"
  become: false
  delegate_to: localhost
  command: kubectl label --overwrite node {{ ansible_hostname }} k3s-upgrade=true
  environment:
    KUBECONFIG: "{{ inventory_dir | dirname }}/kubeconfig"
  when:
  - k3s_system_upgrade == true

- name: "cluster-meta: remove system-upgrade annotations"
  become: false
  delegate_to: localhost
  command: kubectl label --overwrite node {{ ansible_hostname }} k3s-upgrade-
  environment:
    KUBECONFIG: "{{ inventory_dir | dirname }}/kubeconfig"
  when:
  - k3s_system_upgrade == false

- name: "cluster-meta: apply storage annotations"
  become: false
  delegate_to: localhost
  command: kubectl label --overwrite node {{ ansible_hostname }} node.longhorn.io/create-default-disk=true
  environment:
    KUBECONFIG: "{{ inventory_dir | dirname }}/kubeconfig"
  when:
  - longhorn.enabled is defined and longhorn.enabled == true

- name: "cluster-meta: remove storage annotations"
  become: false
  delegate_to: localhost
  command: kubectl label --overwrite node {{ ansible_hostname }} node.longhorn.io/create-default-disk-
  environment:
    KUBECONFIG: "{{ inventory_dir | dirname }}/kubeconfig"
  when:
  - longhorn.enabled is defined and longhorn.enabled == false
