---
- hosts:
  - master
  - worker
  become: true
  gather_facts: false
  vars_prompt:
    name: "nuke_confirmation"
    prompt: "Are you sure you want to run this playbook? This will DESTROY your cluster. (y/N)"
    default: "N"
    private: no
  any_errors_fatal: yes
  tasks:
  - name: check confirmation
    fail: msg="playbook run confirmation failed"
    when: nuke_confirmation != "y"

  - name: "Run k3s-killall.sh"
    command: /usr/local/bin/k3s-killall.sh

  - name: "Run k3s-uninstall.sh"
    command:
      cmd: /usr/local/bin/k3s-uninstall.sh
      removes: /usr/local/bin/k3s-uninstall.sh

  - name: "Run k3s-agent-uninstall.sh"
    command:
      cmd: /usr/local/bin/k3s-agent-uninstall.sh
      removes: /usr/local/bin/k3s-agent-uninstall.sh

  - name: Rebooting hosts
    reboot:
      msg: "Systems are being rebooted"
    ignore_errors: true